FROM ubuntu:focal

#tz
ENV TZ 'Asia/Kolkata'
ENV debian_frontend 'noninteractive'

RUN echo $TZ > /etc/timezone && \
    apt-get update && apt-get install -y tzdata && \
    rm /etc/localtime && \
    ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && \
    dpkg-reconfigure -f noninteractive tzdata && \
    apt-get clean

RUN apt-get install -y aria2 asciidoc automak autoconf gcc g++ python3 python3-pip nano make vim xz

CMD ["bash"]
